handler: src/handlers/settings/raffle/count.handler
name: ${self:service}-${self:provider.stage}-raffle-count
memorySize: ${self:custom.stage.lambda.memorySize}
timeout: ${self:custom.stage.lambda.timeout}
events:
  - httpApi:
      method: GET
      path: /settings/raffle/count
      authorizer:
        name: cognitoJwtAuthorizer
