Type: AWS::DynamoDB::Table
Properties:
  TableName: ${self:custom.settingsTableName}
  AttributeDefinitions:
    - AttributeName: category
      AttributeType: S
    - AttributeName: param
      AttributeType: S
  KeySchema:
    - AttributeName: category
      KeyType: HASH
    - AttributeName: param
      KeyType: RANGE
  BillingMode: PAY_PER_REQUEST

Outputs:
  TableName:
    Description: 'Settings Table Name'
    Value:
      Ref: DynamodbTable
  TableArn:
    Description: 'Settings Table Name'
    Value:
      Fn::GetAtt:
        - DynamodbTable
        - Arn
